// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJSo5u84iZyMOv2ISoq3PA2CrgG4Wvn4M',
    appId: '1:504967218544:web:2d86c54a6a2b0c56c2bbb5',
    messagingSenderId: '504967218544',
    projectId: 'stw-ppt-generator',
    authDomain: 'stw-ppt-generator.firebaseapp.com',
    storageBucket: 'stw-ppt-generator.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaPeS2pYVH39cPEgbHhv29alJG73ZZSjA',
    appId: '1:504967218544:android:6a97ea389a08f7adc2bbb5',
    messagingSenderId: '504967218544',
    projectId: 'stw-ppt-generator',
    storageBucket: 'stw-ppt-generator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUQ-5-Bwb-HYnXhPhBJFhS30rVgUg5oQY',
    appId: '1:504967218544:ios:7bf9aa912b95c4f8c2bbb5',
    messagingSenderId: '504967218544',
    projectId: 'stw-ppt-generator',
    storageBucket: 'stw-ppt-generator.firebasestorage.app',
    iosBundleId: 'com.example.interactivePptClassroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUQ-5-Bwb-HYnXhPhBJFhS30rVgUg5oQY',
    appId: '1:504967218544:ios:7bf9aa912b95c4f8c2bbb5',
    messagingSenderId: '504967218544',
    projectId: 'stw-ppt-generator',
    storageBucket: 'stw-ppt-generator.firebasestorage.app',
    iosBundleId: 'com.example.interactivePptClassroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJSo5u84iZyMOv2ISoq3PA2CrgG4Wvn4M',
    appId: '1:504967218544:web:9f28f1b3e1a408f1c2bbb5',
    messagingSenderId: '504967218544',
    projectId: 'stw-ppt-generator',
    authDomain: 'stw-ppt-generator.firebaseapp.com',
    storageBucket: 'stw-ppt-generator.firebasestorage.app',
  );
}
